#!/usr/bin/php
<?php

/**
 *                   ______                            __
 *           __     /\\\\\\\\_                        /\\\
 *          /\\\  /\\\//////\\\_                      \/\\\
 *        /\\\//  \///     \//\\\    ________       ___\/\\\         _______
 *      /\\\//               /\\\   /\\\\\\\\\_    /\\\\\\\\\       /\\\\\\\\_
 *    /\\\//_              /\\\\/   /\\\/////\\\   /\\\////\\\     /\\\/////\\\
 *    \////\\\ __          /\\\/    \/\\\   \/\\\  \/\\\  \/\\\    /\\\\\\\\\\\
 *        \////\\\ __      \///_     \/\\\___\/\\\  \/\\\__\/\\\   \//\\\//////_
 *            \////\\\       /\\\     \/\\\\\\\\\\   \//\\\\\\\\\    \//\\\\\\\\\
 *                \///       \///      \/\\\//////     \/////////      \/////////
 *                                      \/\\\
 *                                       \///
 *
 *                             P(?:ointless|ortable|HP) Demo Engine/
 */

declare(strict_types = 1);

namespace ABadCafe\PDE;

require_once 'src/PDE.php';

$oDisplay = Display\Factory::get()->create('PlainASCII', 120, 40);
$oRoutine1 = Routine\Factory::get()->create('SimpleLine', $oDisplay, []);
$oRoutine2 = Routine\Factory::get()->create('Toroid', $oDisplay, []);

$oRateLimiter = new System\RateLimiter(30);

$iFrameNumber = 0;
$fTimeIndex   = 0.0;
while ($fTimeIndex < 5.0) {
    $oDisplay->clear();
    $oRoutine1->render($iFrameNumber, $fTimeIndex);
    $oRoutine2->render($iFrameNumber, $fTimeIndex);
    $oDisplay->redraw();
    $fTimeIndex = $oRateLimiter->limit();
    ++$iFrameNumber;
}

echo "Frames:", $iFrameNumber, "\nLimiter skipped ", $oRateLimiter->getNumFramesSkipped(), "\n";
