#!/usr/bin/php
<?php

/**
 *                   ______                            __
 *           __     /\\\\\\\\_                        /\\\
 *          /\\\  /\\\//////\\\_                      \/\\\
 *        /\\\//  \///     \//\\\    ________       ___\/\\\         _______
 *      /\\\//               /\\\   /\\\\\\\\\_    /\\\\\\\\\       /\\\\\\\\_
 *    /\\\//_              /\\\\/   /\\\/////\\\   /\\\////\\\     /\\\/////\\\
 *    \////\\\ __          /\\\/    \/\\\   \/\\\  \/\\\  \/\\\    /\\\\\\\\\\\
 *        \////\\\ __      \///_     \/\\\___\/\\\  \/\\\__\/\\\   \//\\\//////_
 *            \////\\\       /\\\     \/\\\\\\\\\\   \//\\\\\\\\\    \//\\\\\\\\\
 *                \///       \///      \/\\\//////     \/////////      \/////////
 *                                      \/\\\
 *                                       \///
 *
 *                             P(?:ointless|ortable|HP) Demo Engine/
 */

declare(strict_types = 1);

namespace ABadCafe\PDE;

require_once 'src/PDE.php';

$oDisplay     = Display\Factory::get()->create('PlainASCII', 120, 40);
$oRateLimiter = new System\RateLimiter\Simple(30);
$oContext     = new System\Context($oDisplay, $oRateLimiter);

$oContext->registerRoutine(
    Routine\Factory::get()->create('SimpleLine', $oDisplay, []),
    'lines',
    0,
    true
);

$oContext->registerRoutine(
    Routine\Factory::get()->create('Toroid', $oDisplay, []),
    'doughnut',
    20,
    true
);

$oContext->runUntil(20.0);
