<?php

namespace ABadCafe\PDE;

const CLASS_MAP = [
  'ABadCafe\\PDE\\IDisplay' => '/IDisplay.php',
  'ABadCafe\\PDE\\IRoutine' => '/IRoutine.php',
  'ABadCafe\\PDE\\Display\\PlainASCII' => '/display/PlainASCII.php',
  'ABadCafe\\PDE\\Display\\DoubleVerticalRGB' => '/display/DoubleVerticalRGB.php',
  'ABadCafe\\PDE\\Display\\Factory' => '/display/Factory.php',
  'ABadCafe\\PDE\\Display\\BasicRGB' => '/display/BasicRGB.php',
  'ABadCafe\\PDE\\Display\\AsyncRGB' => '/display/AsyncRGB.php',
  'ABadCafe\\PDE\\Display\\IANSIControl' => '/display/common/IANSIControl.php',
  'ABadCafe\\PDE\\Display\\IPixelled' => '/display/common/IPixelled.php',
  'ABadCafe\\PDE\\Display\\TPixelled' => '/display/common/TPixelled.php',
  'ABadCafe\\PDE\\Display\\IASCIIArt' => '/display/common/IASCIIArt.php',
  'ABadCafe\\PDE\\Display\\TASCIIArt' => '/display/common/TASCIIArt.php',
  'ABadCafe\\PDE\\Display\\Base' => '/display/common/Base.php',
  'ABadCafe\\PDE\\Display\\TInstrumented' => '/display/common/TInstrumented.php',
  'ABadCafe\\PDE\\Display\\TAsynchronous' => '/display/common/TAsynchronous.php',
  'ABadCafe\\PDE\\Display\\ICustomChars' => '/display/common/ICustomChars.php',
  'ABadCafe\\PDE\\Routine\\NoOp' => '/routine/NoOp.php',
  'ABadCafe\\PDE\\Routine\\SimpleLine' => '/routine/SimpleLine.php',
  'ABadCafe\\PDE\\Routine\\RGBPulse' => '/routine/RGBPulse.php',
  'ABadCafe\\PDE\\Routine\\Toroid' => '/routine/Toroid.php',
  'ABadCafe\\PDE\\Routine\\Factory' => '/routine/Factory.php',
  'ABadCafe\\PDE\\Routine\\RGBPersistence' => '/routine/RGBPersistence.php',
  'ABadCafe\\PDE\\Routine\\StaticNoise' => '/routine/StaticNoise.php',
  'ABadCafe\\PDE\\Routine\\TRoutine' => '/routine/common/TRoutine.php',
  'ABadCafe\\PDE\\Routine\\Base' => '/routine/common/Base.php',
  'ABadCafe\\PDE\\System\\ILoader' => '/system/ILoader.php',
  'ABadCafe\\PDE\\System\\IRateLimiter' => '/system/IRateLimiter.php',
  'ABadCafe\\PDE\\System\\Context' => '/system/Context.php',
  'ABadCafe\\PDE\\System\\RateLimiter\\Adaptive' => '/system/rate_limiter/Adaptive.php',
  'ABadCafe\\PDE\\System\\RateLimiter\\Simple' => '/system/rate_limiter/Simple.php',
  'ABadCafe\\PDE\\System\\Definition\\TDefinition' => '/system/definition/TDefinition.php',
  'ABadCafe\\PDE\\System\\Definition\\Display' => '/system/definition/Display.php',
  'ABadCafe\\PDE\\System\\Definition\\Event' => '/system/definition/Event.php',
  'ABadCafe\\PDE\\System\\Definition\\Routine' => '/system/definition/Routine.php',
  'ABadCafe\\PDE\\System\\Loader\\JSON' => '/system/loader/JSON.php',
];